---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---  ## separacao de arquivo
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: flask-app-deployment
spec: ## especificar esse aplicativo
  replicas: 4
  selector:
    matchLabels:
      app: flask-app  ## nome do aplicativo
  template:  ## descrevendo como app vai rodar
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: guiar/flask-kub-projeto:6